ALTER TABLE report_project_partner_expenditure_cost_category
    ADD COLUMN staff_current_parked                      DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER sum_previously_reported,
    ADD COLUMN office_current_parked                     DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER staff_current_parked,
    ADD COLUMN travel_current_parked                     DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER office_current_parked,
    ADD COLUMN external_current_parked                   DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER travel_current_parked,
    ADD COLUMN equipment_current_parked                  DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER external_current_parked,
    ADD COLUMN infrastructure_current_parked             DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER equipment_current_parked,
    ADD COLUMN other_current_parked                      DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER infrastructure_current_parked,
    ADD COLUMN lump_sum_current_parked                   DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER other_current_parked,
    ADD COLUMN unit_cost_current_parked                  DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER lump_sum_current_parked,
    ADD COLUMN sum_current_parked                        DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER unit_cost_current_parked,

    ADD COLUMN staff_current_re_included                 DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER sum_current_parked,
    ADD COLUMN office_current_re_included                DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER staff_current_re_included,
    ADD COLUMN travel_current_re_included                DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER office_current_re_included,
    ADD COLUMN external_current_re_included              DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER travel_current_re_included,
    ADD COLUMN equipment_current_re_included             DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER external_current_re_included,
    ADD COLUMN infrastructure_current_re_included        DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER equipment_current_re_included,
    ADD COLUMN other_current_re_included                 DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER infrastructure_current_re_included,
    ADD COLUMN lump_sum_current_re_included              DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER other_current_re_included,
    ADD COLUMN unit_cost_current_re_included             DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER lump_sum_current_re_included,
    ADD COLUMN sum_current_re_included                   DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER unit_cost_current_re_included,

    ADD COLUMN staff_previously_reported_parked          DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER sum_current_re_included,
    ADD COLUMN office_previously_reported_parked         DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER staff_previously_reported_parked,
    ADD COLUMN travel_previously_reported_parked         DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER office_previously_reported_parked,
    ADD COLUMN external_previously_reported_parked       DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER travel_previously_reported_parked,
    ADD COLUMN equipment_previously_reported_parked      DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER external_previously_reported_parked,
    ADD COLUMN infrastructure_previously_reported_parked DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER equipment_previously_reported_parked,
    ADD COLUMN other_previously_reported_parked          DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER infrastructure_previously_reported_parked,
    ADD COLUMN lump_sum_previously_reported_parked       DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER other_previously_reported_parked,
    ADD COLUMN unit_cost_previously_reported_parked      DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER lump_sum_previously_reported_parked,
    ADD COLUMN sum_previously_reported_parked            DECIMAL(17, 2) UNSIGNED NOT NULL DEFAULT 0.00 AFTER unit_cost_previously_reported_parked;

