ALTER TABLE report_project_partner_expenditure_co_financing
    MODIFY COLUMN partner_contribution_total                        DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN public_contribution_total                         DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN automatic_public_contribution_total               DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN private_contribution_total                        DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN sum_total                                         DECIMAL(17, 2) NOT NULL DEFAULT 0.00,

    MODIFY COLUMN partner_contribution_current                      DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN public_contribution_current                       DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN automatic_public_contribution_current             DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN private_contribution_current                      DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN sum_current                                       DECIMAL(17, 2) NOT NULL DEFAULT 0.00,

    MODIFY COLUMN partner_contribution_previously_reported          DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN public_contribution_previously_reported           DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN automatic_public_contribution_previously_reported DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN private_contribution_previously_reported          DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN sum_previously_reported                           DECIMAL(17, 2) NOT NULL DEFAULT 0.00;

ALTER TABLE report_project_partner_expenditure_cost_category
    MODIFY COLUMN staff_total                                 DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN office_total                                DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN travel_total                                DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN external_total                              DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN equipment_total                             DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN infrastructure_total                        DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN other_total                                 DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN lump_sum_total                              DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN unit_cost_total                             DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN sum_total                                   DECIMAL(17, 2) NOT NULL DEFAULT 0.00,

    MODIFY COLUMN staff_current                               DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN office_current                              DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN travel_current                              DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN external_current                            DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN equipment_current                           DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN infrastructure_current                      DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN other_current                               DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN lump_sum_current                            DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN unit_cost_current                           DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN sum_current                                 DECIMAL(17, 2) NOT NULL DEFAULT 0.00,

    MODIFY COLUMN staff_total_eligible_after_control          DECIMAL(17, 2) NOT NULL DEFAULT 0.00 AFTER sum_current,
    MODIFY COLUMN office_total_eligible_after_control         DECIMAL(17, 2) NOT NULL DEFAULT 0.00 AFTER staff_total_eligible_after_control,
    MODIFY COLUMN travel_total_eligible_after_control         DECIMAL(17, 2) NOT NULL DEFAULT 0.00 AFTER office_total_eligible_after_control,
    MODIFY COLUMN external_total_eligible_after_control       DECIMAL(17, 2) NOT NULL DEFAULT 0.00 AFTER travel_total_eligible_after_control,
    MODIFY COLUMN equipment_total_eligible_after_control      DECIMAL(17, 2) NOT NULL DEFAULT 0.00 AFTER external_total_eligible_after_control,
    MODIFY COLUMN infrastructure_total_eligible_after_control DECIMAL(17, 2) NOT NULL DEFAULT 0.00 AFTER equipment_total_eligible_after_control,
    MODIFY COLUMN other_total_eligible_after_control          DECIMAL(17, 2) NOT NULL DEFAULT 0.00 AFTER infrastructure_total_eligible_after_control,
    MODIFY COLUMN lump_sum_total_eligible_after_control       DECIMAL(17, 2) NOT NULL DEFAULT 0.00 AFTER other_total_eligible_after_control,
    MODIFY COLUMN unit_cost_total_eligible_after_control      DECIMAL(17, 2) NOT NULL DEFAULT 0.00 AFTER lump_sum_total_eligible_after_control,
    MODIFY COLUMN sum_total_eligible_after_control            DECIMAL(17, 2) NOT NULL DEFAULT 0.00 AFTER unit_cost_total_eligible_after_control,

    MODIFY COLUMN staff_previously_reported                   DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN office_previously_reported                  DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN travel_previously_reported                  DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN external_previously_reported                DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN equipment_previously_reported               DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN infrastructure_previously_reported          DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN other_previously_reported                   DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN lump_sum_previously_reported                DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN unit_cost_previously_reported               DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN sum_previously_reported                     DECIMAL(17, 2) NOT NULL DEFAULT 0.00,

    MODIFY COLUMN staff_previously_validated                  DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN office_previously_validated                 DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN travel_previously_validated                 DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN external_previously_validated               DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN equipment_previously_validated              DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN infrastructure_previously_validated         DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN other_previously_validated                  DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN lump_sum_previously_validated               DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN unit_cost_previously_validated              DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN sum_previously_validated                    DECIMAL(17, 2) NOT NULL DEFAULT 0.00,

    MODIFY COLUMN staff_current_parked                        DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN office_current_parked                       DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN travel_current_parked                       DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN external_current_parked                     DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN equipment_current_parked                    DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN infrastructure_current_parked               DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN other_current_parked                        DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN lump_sum_current_parked                     DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN unit_cost_current_parked                    DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN sum_current_parked                          DECIMAL(17, 2) NOT NULL DEFAULT 0.00,

    MODIFY COLUMN staff_current_re_included                   DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN office_current_re_included                  DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN travel_current_re_included                  DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN external_current_re_included                DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN equipment_current_re_included               DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN infrastructure_current_re_included          DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN other_current_re_included                   DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN lump_sum_current_re_included                DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN unit_cost_current_re_included               DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN sum_current_re_included                     DECIMAL(17, 2) NOT NULL DEFAULT 0.00,

    MODIFY COLUMN staff_previously_reported_parked            DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN office_previously_reported_parked           DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN travel_previously_reported_parked           DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN external_previously_reported_parked         DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN equipment_previously_reported_parked        DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN infrastructure_previously_reported_parked   DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN other_previously_reported_parked            DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN lump_sum_previously_reported_parked         DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN unit_cost_previously_reported_parked        DECIMAL(17, 2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN sum_previously_reported_parked              DECIMAL(17, 2) NOT NULL DEFAULT 0.00;
