CREATE TABLE programme_state_aid
(
    id            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    measure       ENUM ( 'General de minimis',
        'Road freight de minimis',
        'Agricultural de minimis',
        'Fishery and aquaculture sector de minimis',
        'SGEI de minimis',
        'GBER Article 14',
        'GBER Article 15',
        'GBER Article 16',
        'GBER Article 17',
        'GBER Article 18',
        'GBER Article 19',
        'GBER Article 19a',
        'GBER Article 19b',
        'GBER Article 20',
        'GBER Article 20a',
        'GBER Article 21',
        'GBER Article 22',
        'GBER Article 23',
        'GBER Article 24',
        'GBER Article 25 par. (a)',
        'GBER Article 25 par. (b)',
        'GBER Article 25 par. (c)',
        'GBER Article 25 par. (d)',
        'GBER Article 25a',
        'GBER Article 25b',
        'GBER Article 25c',
        'GBER Article 25d',
        'GBER Article 26',
        'GBER Article 27',
        'GBER Article 28',
        'GBER Article 29',
        'GBER Article 30',
        'GBER Article 31',
        'GBER Article 32',
        'GBER Article 33',
        'GBER Article 34',
        'GBER Article 35',
        'GBER Article 36',
        'GBER Article 36a',
        'GBER Article 37',
        'GBER Article 38',
        'GBER Article 39',
        'GBER Article 40',
        'GBER Article 41',
        'GBER Article 42',
        'GBER Article 43',
        'GBER Article 44',
        'GBER Article 45',
        'GBER Article 46',
        'GBER Article 47',
        'GBER Article 48',
        'GBER Article 49',
        'GBER Article 50',
        'GBER Article 51',
        'GBER Article 52',
        'GBER Article 52a',
        'GBER Article 52b',
        'GBER Article 52c',
        'GBER Article 53',
        'GBER Article 54',
        'GBER Article 55',
        'GBER Article 56',
        'GBER Article 56a',
        'GBER Article 56b',
        'GBER Article 56c',
        'GBER Article 56e',
        'GBER Article 56f',
        'Indirect aid',
        'RDI Framework',
        'SGEI Framework',
        'Other 1',
        'Other 2',
        'Other 3' ) NOT NULL DEFAULT 'Other 1',
    scheme_number VARCHAR(25) DEFAULT NULL,
    max_intensity DECIMAL(5, 2) UNSIGNED DEFAULT 0.00,
    threshold     DECIMAL(17,2)  DEFAULT 0.00
);

CREATE TABLE programme_state_aid_transl
(
    source_entity_id INT UNSIGNED NOT NULL,
    language         VARCHAR(3) NOT NULL,
    name             VARCHAR(150) DEFAULT NULL,
    abbreviated_name VARCHAR(50)  DEFAULT NULL,
    comments         VARCHAR(500) DEFAULT NULL,
    PRIMARY KEY (source_entity_id, language),
    CONSTRAINT fk_programme_state_aid_transl_to_programme_state_aid
        FOREIGN KEY (source_entity_id)
            REFERENCES programme_state_aid (id)
            ON DELETE CASCADE
            ON UPDATE RESTRICT
);
