-- PROCUREMENT

INSERT IGNORE INTO programme_checklist (type, name, min_score, max_score, allows_decimal_score)
VALUES ('CONTROL','HIT - Procurement #TEMP_PROCUREMENT#', '0.00', '10.00', '0');

SELECT id INTO @temp_procurement_id FROM programme_checklist WHERE programme_checklist.name LIKE 'HIT - Procurement #TEMP_PROCUREMENT#';

INSERT IGNORE INTO programme_checklist_component (type, position_on_table, programme_checklist_id, metadata)
VALUES
    ('TEXT_INPUT', 0, @temp_procurement_id, '{"question":"Procurement checklist - one checklist for each procurement","explanationLabel":"Procurement name and amount (excl. VAT)","explanationMaxLength":300}'),
    ('TEXT_INPUT', 1, @temp_procurement_id, '{"question":"Name of purchased services/work/supply","explanationLabel":"Specify all (in case there are more)","explanationMaxLength":300}'),
    ('TEXT_INPUT', 2, @temp_procurement_id, '{"question":"Contractor/Supplier name and VAT number (or other identifier)","explanationLabel":"Specify contractor full name","explanationMaxLength":300}'),
    ('TEXT_INPUT', 3, @temp_procurement_id, '{"question":"Contract reference number and Contract date","explanationLabel":"List also contract amendment dates","explanationMaxLength":1000}'),
    ('HEADLINE', 4, @temp_procurement_id, '{"value":"A. contracts below EUR 10.000 excl. VAT"}'),
    ('OPTIONS_TOGGLE', 5, @temp_procurement_id, '{"question":"A.1 The value for money of costs was ensured and demonstrated","firstOption":"Yes","secondOption":"No","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 6, @temp_procurement_id, '{"question":"A.2 There is no evidence of artificial splitting of the contract objective/value","firstOption":"Yes","secondOption":"No"}'),
    ('HEADLINE', 7, @temp_procurement_id, '{"value":"B. Contracts between EUR 10.000 (excl. VAT) and the threshold set by the applicable EU or national rules"}'),
    ('OPTIONS_TOGGLE', 8, @temp_procurement_id, '{"question":"B.1 Adequate market research was performed and are duly documented (if applicable, according to the national rules and/or programme manual)","firstOption":"Yes","secondOption":"No","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 9, @temp_procurement_id, '{"question":"B.2 There is no evidence of artificial splitting of the contract objective/value.","firstOption":"Yes","secondOption":"No","thirdOption":"N/A"}'),
    ('HEADLINE', 11, @temp_procurement_id, '{"value":"C. Contracts above the threshold set by the applicable National or EU rules (for institutions falling under the scope of application of the public procurement laws"}'),
    ('OPTIONS_TOGGLE', 12, @temp_procurement_id, '{"question":"C.1 EU, national and any other applicable public procurement rules were observed; e.g., \\nComplies with the applicable rules; \\nPublicity requirement were respected; \\nThe principles of transparency, non-discrimination, equal treatment, effective competition have been complied with; \\nThere was a clear distinction between selection and award criteria in the evaluation of the bids;\\nSelection and award criteria and required technical specifications and national permits are transparent, nondiscriminatory and ensure equal treatment;\\nDecisions are properly documented and justified.\\nNo cases of actual or potential conflict of interest came to the attention of the controller, or the conflict of interest policy was followed where applicable","firstOption":"Yes","secondOption":"No","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 13, @temp_procurement_id, '{"question":"C.2\\tThe procurement procedure is documented and available (If documentation is not required, please tick N/A and provide an explanation in the comments section),\\ne.g.\\nInitial cost estimate made by the project partner to identify the applicable public procurement procedure;\\nRequest for offers or procurement publication/notice;\\nTerms of reference (TOR)\\nOffers/quotes received;\\nReport on assessment of bids (evaluation/selection report);\\n Information on acceptance and rejection (notification of bidders);\\n Legal remedies / contradictory procedure / complaints;\\n The contract including any amendments and in line with the selected offer, etc.","firstOption":"Yes","secondOption":"No","thirdOption":"N/A"}'),
    ('TEXT_INPUT', 18, @temp_procurement_id, '{"question":"Description of findings, observations and limitations","explanationLabel":"Refers only to questions above","explanationMaxLength":5000}'),
    ('TEXT_INPUT', 19, @temp_procurement_id, '{"question":"Conclusions and recommendations","explanationLabel":"Refers only to questions above","explanationMaxLength":5000}'),
    ('TEXT_INPUT', 20, @temp_procurement_id, '{"question":"Follow-up measures for the next progress report","explanationLabel":"Refers only to questions above","explanationMaxLength":5000}'),
    ('OPTIONS_TOGGLE', 10, @temp_procurement_id, '{"question":"B.3 (Only in cases where a contract amendment/extension has been issued) Any amendment of the contract is in line with the applicable procurement rules without putting into question the validity of the initial procurement procedure?\\n","firstOption":"Yes","secondOption":"No","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 14, @temp_procurement_id, '{"question":"C.3 There is no evidence of artificial splitting of the contract objective/value.","firstOption":"Yes","secondOption":"No","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 15, @temp_procurement_id, '{"question":"C.4 (Only if the contract was amended or extended)\\nAny amendment of the contract is in line with the relevant public procurement rules without any relevant impact on the validity of the initial procurement procedure. ","firstOption":"Yes","secondOption":"No","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 16, @temp_procurement_id, '{"question":"C.5\\tIf the partner organisation decided to award the contract directly (negotiated procedure without prior publication), the decision is justified and documented.  \\nFor direct awards because of: \\n●\\tUrgency: it is proven that the urgency is due to unforeseeable circumstances.\\n●\\tTechnical/exclusivity reasons: it is ruled out (based on objective evidence) that any other supplier is capable of providing the services.), etc. ","firstOption":"Yes","secondOption":"No","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 17, @temp_procurement_id, '{"question":"C.6 The invoices have been issued and payments have been made in respect of the products and services delivered and the tender (in terms of nature, procurement budget and the amounts fixed in the contract/accepted offer). ","firstOption":"Yes","secondOption":"No","thirdOption":"N/A"}');

-- ELIGIBILITY

INSERT IGNORE INTO programme_checklist (type, name, min_score, max_score, allows_decimal_score)
VALUES ('CONTROL','HIT - Eligibility along cost categories #TEMP_ELIGIBILITY#', '0.00', '10.00', '0');

SELECT id INTO @temp_eligibility_id FROM programme_checklist WHERE programme_checklist.name LIKE 'HIT - Eligibility along cost categories #TEMP_ELIGIBILITY#';

INSERT IGNORE INTO programme_checklist_component (type, position_on_table, programme_checklist_id, metadata)
VALUES
    ('HEADLINE', 3, @temp_eligibility_id, '{"value":"1. Staff costs - in case of Unit costs"}'),
    ('OPTIONS_TOGGLE', 4, @temp_eligibility_id, '{"question":"1.1 Persons who declared staff costs are employees of the beneficiary or work under a contract considered as an employment contract.\\n(e.g. Inspected employment/work contracts and contracts considered as employment contracts of individuals declaring staff costs (part-time and full-time))","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 5, @temp_eligibility_id, '{"question":"1.2 Written agreements exist outlining work for the project\\n( e.g. Inspected agreements of employees declaring staff costs (part-time and full-time))","firstOption":"Yes","secondOption":"Not (fuly)","thirdOption":"N/A"}'),
    ('HEADLINE', 17, @temp_eligibility_id, '{"value":"2. Office and Administration (Flat rate)"}'),
    ('OPTIONS_TOGGLE', 19, @temp_eligibility_id, '{"question":"2.2 There is no double declaration of the cost items in other cost categories\\n(e.g. Verified that no-cost items listed in Art. 4 of Delegated Reg. (EU) No 418/2014 had been included in other cost categories)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('HEADLINE', 21, @temp_eligibility_id, '{"value":"3. Travel and accommodation"}'),
    ('OPTIONS_TOGGLE', 22, @temp_eligibility_id, '{"question":"3.1 (Real cost) Travels are related to the project activities.\\n","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 25, @temp_eligibility_id, '{"question":"3.2 (Flat rate) There is no double declaration of the same cost item in other cost categories. \\n(e.g. Verified that cost items listed in Article 41(1) of the Interreg Regulation had not been included in other cost categories)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('HEADLINE', 27, @temp_eligibility_id, '{"value":"4. External expertise and services"}'),
    ('OPTIONS_TOGGLE', 28, @temp_eligibility_id, '{"question":"4.1 External expertise and services were acquired in this reporting period","firstOption":"Yes  - fill in also public procurement checklist","secondOption":"No","thirdOption":""}'),
    ('OPTIONS_TOGGLE', 29, @temp_eligibility_id, '{"question":"4.2 Providers of services or expertise are external to the project partnership\\n(e.g. Interviewed the project partner to verify that external expert or service providers are not employees of the project partnership) ","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('HEADLINE', 33, @temp_eligibility_id, '{"value":"5. Equipment"}'),
    ('OPTIONS_TOGGLE', 34, @temp_eligibility_id, '{"question":"5.1 New equipment is reported ","firstOption":"Yes  - fill in also public procurement checklist","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 35, @temp_eligibility_id, '{"question":"5.2 The types of costs listed under the cost categories are eligible according to EU and programme rules. \\n(e.g. Verified that the types of costs listed under the cost categories are eligible according to Article 43 of the Interreg Regulation.)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('HEADLINE', 39, @temp_eligibility_id, '{"value":"6. Infrastructure and works "}'),
    ('OPTIONS_TOGGLE', 40, @temp_eligibility_id, '{"question":"6.1 Providers of infrastructure and works are external to the project partnership.","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('HEADLINE', 43, @temp_eligibility_id, '{"value":"7. Lump sums (covering several cost categories)"}'),
    ('OPTIONS_TOGGLE', 44, @temp_eligibility_id, '{"question":"7.1 Amounts are in line with the applicable programme, national and internal rules of the partner organisation.","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('HEADLINE', 46, @temp_eligibility_id, '{"value":"8. Unit costs (covering several cost categories)"}'),
    ('OPTIONS_TOGGLE', 47, @temp_eligibility_id, '{"question":"8.1 Amounts are in line with the applicable programme, national and internal rules of the partner organisation.","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('HEADLINE', 49, @temp_eligibility_id, '{"value":"9. Other costs (staff costs * 40%)"}'),
    ('OPTIONS_TOGGLE', 51, @temp_eligibility_id, '{"question":"9.2 The staff costs are eligible\\n(e.g. Verification of the staff costs will depend on the reimbursement method used (real costs, incl. the fixed percentage method, or unit costs; i.e. flat rate for staff costs cannot be used).)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('TEXT_INPUT', 52, @temp_eligibility_id, '{"question":"Description of findings, observations and limitations","explanationLabel":"Refers only to questions above","explanationMaxLength":5000}'),
    ('TEXT_INPUT', 53, @temp_eligibility_id, '{"question":"Conclusions and recommendations","explanationLabel":"Refers only to questions above","explanationMaxLength":5000}'),
    ('TEXT_INPUT', 54, @temp_eligibility_id, '{"question":"Follow-up measures for the next progress report","explanationLabel":"Refers only to questions above","explanationMaxLength":5000}'),
    ('OPTIONS_TOGGLE', 6, @temp_eligibility_id, '{"question":"1.3 The number of hours worked on the project is documented in a time registration system.\\n(e.g. verified that the timesheets of persons claiming staff costs are in line with the number of working hours claimed.)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 7, @temp_eligibility_id, '{"question":"1.4 The total number of hours declared per person for a given year or month do not exceed the number of hours used for the calculation of the hourly rate (Article 55(3) CPR)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N?A"}'),
    ('HEADLINE', 8, @temp_eligibility_id, '{"value":"1. Staff cost - real cost"}'),
    ('OPTIONS_TOGGLE', 9, @temp_eligibility_id, '{"question":"1.1 Persons who declared staff costs are employees of the project partner or work under a contract considered as an employment document.\\n(e.g. Inspected employment/ work contracts and contracts considered as employment contracts of individuals declaring staff costs (part-time and full-time). )","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 10, @temp_eligibility_id, '{"question":"1.2 A document defining the percentage worked on the project (100% or less) is available (e.g., task assignment letter).\\ne.g. Inspected agreements of persons declaring staff costs (part-time and full-time).","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 11, @temp_eligibility_id, '{"question":"1.3 (in the case of the fixed percentage method – for part-time assignments)\\nThe task assignment document OR other similar documentation defining the tasks and percentage of work on the project per employee exists\\n(e.g. Task assignment document; employment/ work contracts if task assignment (with percentage and tasks is part of the contract) )","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 12, @temp_eligibility_id, '{"question":"1.4 (in the case of the fixed percentage method – for part-time assignments)\\nThe task assignment document OR other similar documentation defining the tasks and percentage of work on the project per employee is up-to-date\\n(e.g. The correct version (valid from) of the task assignment document is in place.)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 13, @temp_eligibility_id, '{"question":"1.5 (in the case of the fixed percentage method – for part-time assignments)\\nThe fixed percentage worked on the project is plausible in relation to tasks and acitivites within the project and the job profile of the employee. ","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 14, @temp_eligibility_id, '{"question":"1.6 The percentage worked on the project is correctly applied to calculate the eligible staff costs. ","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 15, @temp_eligibility_id, '{"question":"1.7 If the staff is involved in several projects, it is ensured that not more than 100% of the time is reported (e.g., task assignment letters for all projects are not for more than 100%).","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 16, @temp_eligibility_id, '{"question":"1.8 Staff costs to which the percentage is applied are limited to salary payments and other costs directly linked to salary payments incurred and paid by the employer for the employee working on the project. \\n(e.g. Inspected, e.g. payrolls/payslips, print-out of accounting system, etc. of employees working on the project (part-time and full-time) and verified that staff costs are based on salary payments plus any other costs directly linked to salary payments incurred and paid by the employer such as employment taxes and social security including pensions provided that they are:\\n(i) fixed  in  an  employment  document  or  by  law;  \\n(ii) in  accordance  with  the  legislation  refer red  to  in  the  employment  document  and  with  standard  practices  in  the  country  and/or  organisation  where  the  individual  staff  member  is  actually  working;  and  \\n(iii) not recoverable by the employer.)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 23, @temp_eligibility_id, '{"question":"3.2 (Real cost) Travel and accommodation costs relate to the partner organisation\\u0027s staff or natural persons who work under a contract considered as employment document of the partner organisation or associated partners.\\n(e.g. Inspected invoices and documents of equivalent probative value to ensure that costs were incurred by employees or persons working under contracts considered as employment contracts. Inspected that travel costs of external experts are  included under External expertise and services category)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 30, @temp_eligibility_id, '{"question":"4.3 The types of costs listed under this cost category are eligible according to EU and programme rules. \\n(e.g. Verified that the types of costs listed under this cost category are eligible according to Article 42 of the Interreg Regulation)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 31, @temp_eligibility_id, '{"question":"4.4 Invoices or documents of equivalent probative value are in line with the contract(s) or, where applicable, with the selected offer, in terms of amount and nature.\\n(e.g. Inspected invoices and documents of equivalent probative value to verify that they are in accordance with the contract(s).)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 32, @temp_eligibility_id, '{"question":"4.5 (in the case of experts or services that are NOT exclusively used for the project) \\nThe share allocated to the project is plausible; i.e., calculated according to a fair, equitable and verifiable method. \\n(e.g. Verified that only a share of the expenditure is allocated to the project and that this share is calculated according to a fair, equitable and verifiable method)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 36, @temp_eligibility_id, '{"question":"5.3 Invoices or documents of equivalent probative value are in line with the contract(s) or, where applicable, the selected offer in terms of amount and nature\\n(e.g. Inspected invoices and documents of equivalent probative value to verify that they are in accordance with the contracts in terms of amount and nature.)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 37, @temp_eligibility_id, '{"question":"5.4 The method used to calculate equipment expenditure (full costs, pro rata, depreciation) is correctly applied in line with EU and programme rules. \\n(e.g, Verified that the calculation methods used complies with rules . \\ne.g. For pro-rata calculation, the share allocated to the project is based on a fair, equitable and verifiable calculation method. \\nE.g. For depreciation: it is in line with Article 67(2) CPR and programme rules)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 38, @temp_eligibility_id, '{"question":"5.5 Equipment is available and used for the intended project purpose","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 41, @temp_eligibility_id, '{"question":"6.2 Invoices or documents of equivalent probative value are in line with the contract(s) or, where applicable, the selected offer in terms of amount and nature.\\n(e.g. Inspected invoices and documents of equivalent probative value to verify that they are in accordance with the contract(s) or selected offers)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 42, @temp_eligibility_id, '{"question":"6.3 (in the case of infrastructure and works  that are NOT exclusively used for the project) \\nThe share allocated to the project is plausible; i.e., calculated according to a fair, equitable and verifiable method.\\n(e.g. Verified that only a share of the expenditure is allocated to the project and that this share is calculated according to a fair, equitable and verifiable method)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 45, @temp_eligibility_id, '{"question":"7.2 If relevant, did the activity/event take place and are potential deliverables of service provided?","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 48, @temp_eligibility_id, '{"question":"8.2 If relevant, did the activity/event take place and are potential deliverables of service provided? (e.g. Events, services delivered)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 24, @temp_eligibility_id, '{"question":"3.1 The flat rate is calculated correctly\\n(e.g. The correct percentage is applied on top of the direct staff costs of the partner)","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 26, @temp_eligibility_id, '{"question":"3.3 The staff costs are eligible\\n(e.g. Verification of the staff costs will depend on the reimbursement method used)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 18, @temp_eligibility_id, '{"question":"2.1 The flat rate is calculated correctly.\\n(e.g. The correct percentage is applied)","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 20, @temp_eligibility_id, '{"question":"2.3 The basis costs to calculate flat rate are eligible\\n(e.g. Verification of the basis  costs will depend on the reimbursement method used.)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 50, @temp_eligibility_id, '{"question":"9.1 The flat rate is calculated correctly\\n(e.g. The correct percentage is applied on top of the eligible direct staff costs)","firstOption":"Yes","secondOption":"No"}'),
    ('HEADLINE', 0, @temp_eligibility_id, '{"value":"1. Staff costs - SCO"}'),
    ('OPTIONS_TOGGLE', 1, @temp_eligibility_id, '{"question":"The staff calculation option is in line with programme rules. \\n(e.g. Verified that the flat rate for staff costs is in line with the programme rules and the subsidy contract.)","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 2, @temp_eligibility_id, '{"question":"Staff costs are calculated correctly\\n(e.g. Recalculated simplified staff costs using the calculation scheme. \\n(in the case of up to 20% flat rate): \\nStaff costs calculated on a flat rate basis are up to 20% of the direct costs other than staff costs of that project partner \\ne.g. In the case of unit costs, the multiplication is correct (number of hours reported multiplied by the unit cost as set in programme eligibility rules)","firstOption":"Yes","secondOption":"No"}');

-- ACCOUNTING

INSERT IGNORE INTO programme_checklist (type, name, min_score, max_score, allows_decimal_score)
VALUES ('CONTROL','HIT - Accounting system, VAT, Bank account and Audit trail #TEMP_ACCOUNTING#', '0.00', '10.00', '0');

SELECT id INTO @temp_accounting_id FROM programme_checklist WHERE programme_checklist.name LIKE 'HIT - Accounting system, VAT, Bank account and Audit trail #TEMP_ACCOUNTING#';

INSERT IGNORE INTO programme_checklist_component (type, position_on_table, programme_checklist_id, metadata)
VALUES
    ('HEADLINE', 0, @temp_accounting_id, '{"value":"1.1 Accounting system"}'),
    ('OPTIONS_TOGGLE', 1, @temp_accounting_id, '{"question":"1.1.1 Project partner maintains separate accounting records/system, or accounting code, for all transactions related to the project. Ensuring separation of project expenditure for all transactions relating to the project \\n[according to Art. 74 1a(i) of Reg. (EU) No 2021/1060)]","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 2, @temp_accounting_id, '{"question":"1.1.2 Double-financing is excluded \\n(e.g.,accounting system avoids the allocation of the same invoice to different projects and time recording system for staff prevents any duplication)","firstOption":"Yes - describe how","secondOption":"No - provide explanations"}'),
    ('HEADLINE', 3, @temp_accounting_id, '{"value":"1.2 VAT"}'),
    ('OPTIONS_TOGGLE', 4, @temp_accounting_id, '{"question":"1.2.1 Is the size of the project equal to / over 5 million Euro (incl. VAT)?","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 5, @temp_accounting_id, '{"question":"1.2.2. The partner organisation has the right to recover VAT. \\nPlease provide comments if \\u0027partially\\u0027 is ticked. ","firstOption":"Yes","secondOption":"Partially","thirdOption":"No"}'),
    ('HEADLINE', 6, @temp_accounting_id, '{"value":"1.3 Bank account"}'),
    ('OPTIONS_TOGGLE', 7, @temp_accounting_id, '{"question":"1.3 Correct IBAN is used for the transfer of programme funds and belongs to the partner organisation","firstOption":"Yes","secondOption":"No"}'),
    ('HEADLINE', 8, @temp_accounting_id, '{"value":"1.4 Audit trail"}'),
    ('OPTIONS_TOGGLE', 9, @temp_accounting_id, '{"question":"1.4.1 The partnership agreement is signed by the project partner and latest version is available ","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 10, @temp_accounting_id, '{"question":"1.4.2 Costs are correctly recorded in the partner accounting system ","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 11, @temp_accounting_id, '{"question":"1.4.3 The source of the partner’s contribution (private or public) is correctly indicated.","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 12, @temp_accounting_id, '{"question":"1.4.4 Costs are directly related to the project and necessary for the development or implementation of the project.\\n(e.g. Verified tht:\\n•\\t Costs have been initially planned in the AF under this cost category OR\\n•\\tA written agreement of these costs exists from the JS\\n•\\tCosts are justified in the Report and within programme flexibility rule)","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 13, @temp_accounting_id, '{"question":"1.4.5 Costs are correctly allocated to the relevant cost categories.\\n(e.g. Inspected list of expenditures)","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 14, @temp_accounting_id, '{"question":"1.4.6 Costs are declared only once\\n(e.g. Inspected the list of expenditure and verified that expenditures had not been declared twice in different cost categories or in previous reporting periods)","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 15, @temp_accounting_id, '{"question":"1.4.7 (NOT needed for flat rates, standard scales of unit costs, lump sums, depreciation)\\nExpenditure was incurred and paid in project eligibility period and supported by proof of payment.\\n[according to Art 63(2), Article 67(2) and Art 74 1a(i) of Reg.(EU) No 2021/1060] \\n(e.g., Verified that preparation expenditure foreseen in the approved AF is incurred between 1 January 2021 and the date of the approval of the AF by MC.\\ne.g. Implementation expenditure is incurred and paid within the starting date of the project set in the co-financing contract and the end of the relevant reporting period.)","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 16, @temp_accounting_id, '{"question":"1.4.8  (NOT needed for flat rates, standard scales of unit costs, lump sums, depreciation)\\nExpenditure is supported by invoices or documents of equivalent probative value, which are correct in content and accounting terms.","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 17, @temp_accounting_id, '{"question":"1.4.9 Ineligible costs according to the Regulations and programme rules are excluded from the Report\\n(e.g. Art. 64 of  Reg.(EU) No 2021/1060 )","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 18, @temp_accounting_id, '{"question":"1.4.10 VAT, except for operations set in the Art 64(1)(c) of Reg. (EU) No 2021/1060, was deducted","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 19, @temp_accounting_id, '{"question":"1.4.11 The co-financed products and services were delivered, or delivery is in progress.\\n(e.g. Inspected project evidence provided with the partner report, in particular agendas and signed attendance lists of meetings, written outputs, pictures, etc\\nOR performed own research, in particular search on the internet, OR obtained external confirmation of the project\\u0027s existence, in particular from...\\u0027 or \\u0027Inspected the project partner and activities on the spot. \\nIn the Case of the Last implementation Report)","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 20, @temp_accounting_id, '{"question":"1.4.12 Project partner has received the programme funds from the previous periods within the timeframe agreed by all partners. \\n(e.g., Inspected in the bank statement)","firstOption":"Yes","secondOption":"No","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 21, @temp_accounting_id, '{"question":"1.4.13 The total partner budget, and budget per cost category were respected. \\n(e.g. Verified that accumulated partner expenditure is within the partner budget of the latest version of the approved AF. If not, differences have been covered by the budget flexibility or explained/approved by the [Select: Lead Partner, Joint Secretariat, Managing Authority, Monitoring Committee].)","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 22, @temp_accounting_id, '{"question":"1.4.14 If the partner contribution does not come from the partner\\u0027s own resources but from an external public source, the total public contribution has not been exceeded","firstOption":"Yes","secondOption":"No"}'),
    ('TEXT_INPUT', 23, @temp_accounting_id, '{"question":"Description of findings, observations and limitations","explanationLabel":"Refers only to questions above","explanationMaxLength":5000}'),
    ('TEXT_INPUT', 24, @temp_accounting_id, '{"question":"Conclusions and recommendations","explanationLabel":"Refers only to questions above","explanationMaxLength":5000}'),
    ('TEXT_INPUT', 25, @temp_accounting_id, '{"question":"Follow-up measures for the next progress report","explanationLabel":"Refers only to questions above","explanationMaxLength":5000}');

-- COMPLIANCE

INSERT IGNORE INTO programme_checklist (type, name, min_score, max_score, allows_decimal_score)
VALUES ('CONTROL','HIT - Compliance with info&publicity&other EU rules #TEMP_COMPLIANCE#', '0.00', '10.00', '0');

SELECT id INTO @temp_compliance_id FROM programme_checklist WHERE programme_checklist.name LIKE 'HIT - Compliance with info&publicity&other EU rules #TEMP_COMPLIANCE#';

INSERT IGNORE INTO programme_checklist_component (type, position_on_table, programme_checklist_id, metadata)
VALUES
    ('HEADLINE', 0, @temp_compliance_id, '{"value":"1. Compliance with information and publicity requirements  "}'),
    ('OPTIONS_TOGGLE', 1, @temp_compliance_id, '{"question":"1.1 Information and publicity rules of the EU were complied with\\n(e.g. Inspected project publicity items, including brochures, agendas of conferences, studies and deliverables to ensure they meet the publicity requirements outlined in Annex XII CPR.)","firstOption":"Yes","secondOption":" Not (fully)"}'),
    ('OPTIONS_TOGGLE', 2, @temp_compliance_id, '{"question":"1.2 All communication and visibility material is made available upon request, and use of such material is granted to the Union \\n(e.g. Communication and visibility material has been inspected and contains Union rights of use according to Article 47 CPR )","firstOption":"Yes","secondOption":"Not (fully)"}'),
    ('HEADLINE', 3, @temp_compliance_id, '{"value":"2. Compliance with other EU rules"}'),
    ('OPTIONS_TOGGLE', 4, @temp_compliance_id, '{"question":"2.1 There is no evidence that the project activities do not comply with the EU horizontal principle of sustainable development\\n[according to Article 3 of the Treaty on the European Union (TEU)]\\n(e.g. Compared the partner report to the AF and verified that activities are in line with the AF and do not raise any new issues)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 5, @temp_compliance_id, '{"question":"2.2 There is no evidence that equipment purchased does not comply with EU and national legislation in terms of environmental impacts, required permits, etc.\\ne.g. Verified based on my professional judgement as a controller that compulsory requirements set by the EU and national legislation related to respective equipment are  fulfilled (e.g. environmental impacts, permits, etc.)","firstOption":"Yen","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 6, @temp_compliance_id, '{"question":"2.3 There is no evidence that infrastructure and works do not comply with EU and national legislation in terms of environmental impacts, required permits, etc.\\n(e.g. Verified based on my professional judgement as a controller that compulsory requirements set by the EU and national legislation related to respective infrastructure and works are fulfilled (e.g. environmental)","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('TEXT_INPUT', 9, @temp_compliance_id, '{"question":"Description of findings, observations and limitations","explanationLabel":"Refers only to questions above","explanationMaxLength":5000}'),
    ('TEXT_INPUT', 10, @temp_compliance_id, '{"question":"Conclusions and recommendations","explanationLabel":"Refers only to questions above","explanationMaxLength":5000}'),
    ('TEXT_INPUT', 11, @temp_compliance_id, '{"question":"Follow-up measures for the next progress report","explanationLabel":"Refers only to questions above","explanationMaxLength":5000}'),
    ('OPTIONS_TOGGLE', 7, @temp_compliance_id, '{"question":"2.4 Based on the available information,the project activities comply with the EU horizontal principle of gender equality and non-discrimination. \\n(e.g. Compared the partner report to the AF and verified that activities are in line with the AF and do not raise any new issues.)","firstOption":"Yes","secondOption":"Not (fully)"}'),
    ('OPTIONS_TOGGLE', 8, @temp_compliance_id, '{"question":"2.5 Based on the available information the project activities comply with EU and programme rules on State Aid. \\n(e.g. Compared the partner report to the AF and verified that activities are in line with the AF and do not raise any new issues.\\ne.g. Verified that the project partner does not exceed the de minimis threshold and is not \\u0027in difficulty\\u0027.)","firstOption":"Yes","secondOption":"Not (fully)"}');

-- ONTHESPOT

INSERT IGNORE INTO programme_checklist (type, name, min_score, max_score, allows_decimal_score)
VALUES ('CONTROL','HIT - On-the-spot verification #TEMP_ONTHESPOT#', '0.00', '10.00', '0');

SELECT id INTO @temp_onthespot_id FROM programme_checklist WHERE programme_checklist.name LIKE 'HIT - On-the-spot verification #TEMP_ONTHESPOT#';

INSERT IGNORE INTO programme_checklist_component (type, position_on_table, programme_checklist_id, metadata)
VALUES
    ('TEXT_INPUT', 0, @temp_onthespot_id, '{"question":"On the sport verification general info ","explanationLabel":"Date/period, who performed + any relevant details","explanationMaxLength":5000}'),
    ('OPTIONS_TOGGLE', 1, @temp_onthespot_id, '{"question":"1.1 Documents submitted match the originals","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 2, @temp_onthespot_id, '{"question":"1.2 Documents are correctly archived","firstOption":"Yes","secondOption":"Not (fully)","thirdOption":"N/A"}'),
    ('OPTIONS_TOGGLE', 3, @temp_onthespot_id, '{"question":"Other questions by programmes... ","firstOption":"Yes","secondOption":"No"}'),
    ('TEXT_INPUT', 4, @temp_onthespot_id, '{"question":"Description of findings, observations and limitations","explanationLabel":"Refers only to questions above","explanationMaxLength":5000}'),
    ('TEXT_INPUT', 5, @temp_onthespot_id, '{"question":"Conclusions and recommendations","explanationLabel":"Refers only to questions above","explanationMaxLength":5000}'),
    ('TEXT_INPUT', 6, @temp_onthespot_id, '{"question":"Follow-up measures for the next progress report","explanationLabel":"Refers only to questions above","explanationMaxLength":5000}');

-- AFADMISSION

INSERT IGNORE INTO programme_checklist (type, name, min_score, max_score, allows_decimal_score)
VALUES ('APPLICATION_FORM_ASSESSMENT', 'HIT - Admissibility and eligibility checks #TEMP_AFADMISSION#', '0.00', '10.00', '1');

SELECT id INTO @temp_afadmission_id FROM programme_checklist WHERE programme_checklist.name LIKE 'HIT - Admissibility and eligibility checks #TEMP_AFADMISSION#';

INSERT IGNORE INTO programme_checklist_component (type, position_on_table, programme_checklist_id, metadata)
VALUES
    ('HEADLINE', 1, @temp_afadmission_id, '{"value":"If any of the following questions is NO, the project isn\\u0027t formally compliant OR isn\\u0027t admissible."}'),
    ('HEADLINE', 0, @temp_afadmission_id, '{"value":"Admissibility and eligibility  checks"}'),
    ('OPTIONS_TOGGLE', 2, @temp_afadmission_id, '{"question":"\\nObligatory annexes are attached to the application form, where applicable. ","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 3, @temp_afadmission_id, '{"question":"Supporting documents (e.g., technical investment documentation) are attached, where applicable.","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 4, @temp_afadmission_id, '{"question":"The application form and its annexes are signed, where necessary, according to the programme rules.","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 5, @temp_afadmission_id, '{"question":"The application package is in the required language(s). If applicable, annexes issued by third parties, in other languages than required, are accompanied by their translation.","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 6, @temp_afadmission_id, '{"question":"All applicable sections of the application form are correctly filled in. There is no incorrect information.","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 7, @temp_afadmission_id, '{"question":"Information presented in the application form and in annexes is consistent (e.g., co-financing amounts, partner names, etc.).","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 8, @temp_afadmission_id, '{"question":"The Lead Partner has selected two joint cooperation criteria (for OMR) or three cooperation criteria (for Interreg programmes). ","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 9, @temp_afadmission_id, '{"question":"The Lead partner is an eligible organisation. Programme to decide the rules; e.g., legal status, territorial eligibility – area.\\n\\nNote: This check is separate from other partners because LP has more requirements than other partners. ","firstOption":"Yes","secondOption":"No"}'),
    ('OPTIONS_TOGGLE', 10, @temp_afadmission_id, '{"question":"All project partners are eligible organisations. Programme to decide the rules; e.g., legal status, territorial eligibility – area. ","firstOption":"Yes","secondOption":"No"}');

-- AFQUALITY

INSERT IGNORE INTO programme_checklist (type, name, min_score, max_score, allows_decimal_score)
VALUES ('APPLICATION_FORM_ASSESSMENT', 'HIT - Quality assessment criteria #TEMP_AFQUALITY#', '0.00', '10.00', '1');

SELECT id INTO @temp_afquality_id FROM programme_checklist WHERE programme_checklist.name LIKE 'HIT - Quality assessment criteria #TEMP_AFQUALITY#';

INSERT IGNORE INTO programme_checklist_component (type, position_on_table, programme_checklist_id, metadata)
VALUES
    ('HEADLINE', 0, @temp_afquality_id, '{"value":"Quality assessment criteria "}'),
    ('HEADLINE', 1, @temp_afquality_id, '{"value":"Criteria for assessing the relevance and feasibility of project proposals on which a judgment or decision as to whether the project should be funded will be based."}'),
    ('HEADLINE', 2, @temp_afquality_id, '{"value":"Strategic assessment criteria"}'),
    ('SCORE', 4, @temp_afquality_id, '{"question":"How well is the need for the project justified?","weight":1}'),
    ('SCORE', 5, @temp_afquality_id, '{"question":"The project addresses common territorial challenges of the programme or a joint asset of the programme area - there is a real need for the project (well justified, reasonable, well explained). – AF C.2.1 and C.2.2","weight":1}'),
    ('SCORE', 6, @temp_afquality_id, '{"question":"The project clearly contributes to a wider strategy on one or more policy levels (EU / national / regional). – AF C.2.5","weight":1}'),
    ('SCORE', 7, @temp_afquality_id, '{"question":"To what extent will the project contribute to the achievement of programme’s objectives and indicators?","weight":1}'),
    ('SCORE', 8, @temp_afquality_id, '{"question":"The project overall objective clearly contributes to the achievement of the programme priority specific objective. – AF C.1","weight":1}'),
    ('SCORE', 9, @temp_afquality_id, '{"question":"The project outputs clearly link to programme output indicators and their contribution to programme targets is sufficient. – AF C.4 Output tables in work packages","weight":1}'),
    ('SCORE', 10, @temp_afquality_id, '{"question":"Project’s contribution to programme result indicators is realistic and sufficient. ","weight":1}'),
    ('SCORE', 11, @temp_afquality_id, '{"question":"How does the project build on existing practices?","weight":1}'),
    ('SCORE', 12, @temp_afquality_id, '{"question":"The project makes use of available knowledge and builds on existing results and practices. – AF C.2.7","weight":1}'),
    ('SCORE', 13, @temp_afquality_id, '{"question":"The project tries to avoid overlaps and replications; there is evolution of ideas. – AF C.2.2","weight":1}'),
    ('SCORE', 14, @temp_afquality_id, '{"question":"The project demonstrates new solutions that go beyond the existing practice in the sector/programme area/participating countries or adapts and implements already developed solutions. – AF C.2.2","weight":1}'),
    ('HEADLINE', 15, @temp_afquality_id, '{"value":"Cooperation character "}'),
    ('SCORE', 16, @temp_afquality_id, '{"question":"What added-value does the cooperation bring?","weight":1}'),
    ('SCORE', 17, @temp_afquality_id, '{"question":"The importance of cooperation beyond borders for the topic addressed is clearly demonstrated. – AF C.2.3","weight":1}'),
    ('SCORE', 18, @temp_afquality_id, '{"question":"The results cannot/only to some extent be achieved without cooperation. – AF C.2.3","weight":1}'),
    ('SCORE', 19, @temp_afquality_id, '{"question":"There is a clear benefit from cooperating for the project partners / target groups / project area / programme area. – AF C.2.3","weight":1}'),
    ('HEADLINE', 3, @temp_afquality_id, '{"value":" Project relevance"}'),
    ('HEADLINE', 20, @temp_afquality_id, '{"value":"Project intervention logic"}'),
    ('SCORE', 21, @temp_afquality_id, '{"question":"To what extent is project intervention logic plausible?","weight":1}'),
    ('SCORE', 22, @temp_afquality_id, '{"question":"Project specific objectives are specific, realistic and achievable. – AF C.4 Specific objectives in work packages","weight":1}'),
    ('SCORE', 23, @temp_afquality_id, '{"question":"Proposed project outputs are needed to achieve project specific objectives. – AF C.4 Output tables in work packages","weight":1}'),
    ('SCORE', 24, @temp_afquality_id, '{"question":"Project outputs and results that contribute to programme indicators are realistic (it is possible to achieve them with given resources – i.e., time, partners, budget - and they are realistic based on the quantification provided). – AF C.4, C.5, C.6, D","weight":1}'),
    ('SCORE', 25, @temp_afquality_id, '{"question":"To what extent will project outputs have an impact beyond project lifetime?","weight":1}'),
    ('SCORE', 26, @temp_afquality_id, '{"question":"Project outputs are durable (the proposal is expected to provide a significant and durable contribution to solving the challenges targeted) – if not, it is justified. – AF C.8.2","weight":1}'),
    ('SCORE', 27, @temp_afquality_id, '{"question":"Project main outputs are applicable and replicable by other organisations/regions/countries outside of the current partnership (transferability) – if not, it is justified. – AF C.8.3","weight":1}'),
    ('HEADLINE', 28, @temp_afquality_id, '{"value":"Partnership relevance"}'),
    ('SCORE', 29, @temp_afquality_id, '{"question":"To what extent is the partnership composition relevant for the proposed project?","weight":1}'),
    ('SCORE', 30, @temp_afquality_id, '{"question":"The project involves the relevant actors needed to address the territorial challenge/joint asset and the objectives specified. – AF C.3","weight":1}'),
    ('SCORE', 31, @temp_afquality_id, '{"question":"With respect to the project’s objectives, the project partnership: – AF C.3\\no\\tis balanced with respect to the levels, sectors, territory\\no\\tconsists of partners that complement each other.\\n","weight":1}'),
    ('SCORE', 32, @temp_afquality_id, '{"question":"Partner organisations have proven experience and competence in the thematic field concerned, as well as the necessary capacity to implement the project (financial, human resources, etc.)  – AF B.1.6","weight":1}'),
    ('SCORE', 33, @temp_afquality_id, '{"question":"All partners play a defined role in the partnership and the territory benefits from this cooperation. – AF C.3","weight":1}'),
    ('HEADLINE', 34, @temp_afquality_id, '{"value":"Operational assessment criteria"}'),
    ('HEADLINE', 35, @temp_afquality_id, '{"value":"Work plan"}'),
    ('SCORE', 36, @temp_afquality_id, '{"question":"To what extent is the work plan realistic, consistent and coherent?","weight":1}'),
    ('SCORE', 37, @temp_afquality_id, '{"question":"Proposed activities and deliverables are relevant and lead to planned outputs and results. – AF C.4, C.5","weight":1}'),
    ('SCORE', 38, @temp_afquality_id, '{"question":"Distribution of tasks among partners is appropriate (e.g., sharing of tasks is clear, logical, in line with partners’ role in the project, etc.). – AF C.4 Activities in work packages","weight":1}'),
    ('SCORE', 39, @temp_afquality_id, '{"question":"Time plan is realistic. – AF C.6","weight":1}'),
    ('SCORE', 40, @temp_afquality_id, '{"question":"Activities, deliverables and outputs are in a logical time-sequence. – AF C.6","weight":1}'),
    ('SCORE', 41, @temp_afquality_id, '{"question":"The importance of investments and their transnational/cross-border relevance is demonstrated to reach project objectives (if applicable). – AF C.4 Investments","weight":1}'),
    ('HEADLINE', 42, @temp_afquality_id, '{"value":"Communication"}'),
    ('SCORE', 43, @temp_afquality_id, '{"question":"To what extent are communication activities appropriate to reach the relevant target groups and stakeholders?","weight":1}'),
    ('SCORE', 44, @temp_afquality_id, '{"question":"The communication objectives are relevant and are expected to contribute to project specific objectives. – AF C.4 Objectives in work packages","weight":1}'),
    ('SCORE', 45, @temp_afquality_id, '{"question":"Communication activities (and deliverables) are appropriate to reach the relevant target groups and stakeholders. – AF C.4 Activities and deliverables in work packages","weight":1}'),
    ('HEADLINE', 46, @temp_afquality_id, '{"value":"Budget"}'),
    ('SCORE', 47, @temp_afquality_id, '{"question":"To what extent is the project budget used in accordance with the principles of economy, efficiency and effectiveness?","weight":1}'),
    ('SCORE', 48, @temp_afquality_id, '{"question":"The principle of economy concerns minimising the costs of resources. The resources used by the project partnership for its activities should be made available in due time, in appropriate quantity and quality, and at the best price.\\n-\\tThe budget allocated to staff and external expertise is in line with the project content and the costs are realistic. – AF D.2 \\u0026 E.3\\n-\\tSufficient and reasonable resources are planned to ensure project implementation. – AF D.2 \\u0026 E.3","weight":1}'),
    ('SCORE', 49, @temp_afquality_id, '{"question":"The principle of efficiency concerns getting the most from the available resources. It is concerned with the relationship between resources employed and outputs delivered in terms of quantity, quality and timing.\\n-\\tThe need for engaging external expertise is justified and the costs seem realistic. – AF D3\\n-\\tFinancial allocation per cost category is in line with the work plan. – AF D.2 \\u0026 D.3\\n-\\tIf applicable, the distribution of the budget per period is in line with the work plan. – AF D.4\\n-\\tThe application of lump sums and unit costs is appropriate and in line with the programme rules. – AF D.2 \\u0026 D.3","weight":1}'),
    ('SCORE', 50, @temp_afquality_id, '{"question":"•\\tThe principle of effectiveness concerns meeting the objectives and achieving the intended results.\\n-\\tThe available information in the budget is transparent and sufficient. On that basis, the project budget appears proportionate to the proposed work plan, project outputs and project\\u0027s contribution to programme indicators aimed for. – AF D.2 \\u0026 D3\\n-\\tSufficient and reasonable resources are planned for investments and equipment purchases (if applicable) and their costs are realistic. – AF D.2 \\u0026 D3","weight":1}');
