package io.cloudflight.ems.audit.entity

enum class AuditAction {
    // package CALL
    CALL_CREATED,
    CALL_PUBLISHED,

    // package INDICATOR
    PROGRAMME_INDICATOR_ADDED,
    PROGRAMME_INDICATOR_EDITED,

    // package NUTS
    NUTS_DATASET_DOWNLOAD,

    // package PROGRAMME
    PROGRAMME_PRIORITY_ADDED,
    PROGRAMME_BASIC_DATA_EDITED,
    PROGRAMME_NUTS_AREA_CHANGED,
    PROGRAMME_FUNDS_CHANGED,

    // package PROJECT
    APPLICATION_STATUS_CHANGED,
    CALL_ALREADY_ENDED,
    QUALITY_ASSESSMENT_CONCLUDED,
    ELIGIBILITY_ASSESSMENT_CONCLUDED,

    // messages related to FILEs
    PROJECT_FILE_DELETED,
    PROJECT_FILE_UPLOADED_SUCCESSFULLY,
    PROJECT_FILE_UPLOAD_FAILED,
    PROJECT_FILE_DESCRIPTION_CHANGED,

    // package SECURITY
    USER_LOGGED_IN,
    USER_LOGGED_OUT,
    USER_SESSION_EXPIRED,

    // package USER
    USER_CREATED,
    USER_REGISTERED,
    USER_ROLE_CHANGED,
    PASSWORD_CHANGED,
    USER_DATA_CHANGED,

}
