package io.cloudflight.jems.server.project.service.partner.budget.update_budget_general_costs.update_budget_external_expertise_and_services

import io.cloudflight.jems.server.project.service.partner.budget.update_budget_general_costs.UpdateBudgetGeneralCostsInteractor

interface UpdateBudgetExternalExpertiseAndServicesCostsInteractor : UpdateBudgetGeneralCostsInteractor
