package io.cloudflight.jems.api.project.dto.status

enum class ApplicationStatusDTO {
    STEP1_DRAFT,
    STEP1_SUBMITTED,
    STEP1_ELIGIBLE,
    STEP1_INELIGIBLE,
    STEP1_APPROVED,
    STEP1_APPROVED_WITH_CONDITIONS,
    STEP1_NOT_APPROVED,
    DRAFT,
    SUBMITTED,
    CONDITIONS_SUBMITTED,
    RETURNED_TO_APPLICANT,
    RETURNED_TO_APPLICANT_FOR_CONDITIONS,
    ELIGIBLE,
    INELIGIBLE,
    APPROVED,
    APPROVED_WITH_CONDITIONS,
    MODIFICATION_PRECONTRACTING,
    MODIFICATION_PRECONTRACTING_SUBMITTED,
    MODIFICATION_REJECTED,
    NOT_APPROVED
}
