version: '3.6'

services:
  mongo:
    image: mongo:4.2
    volumes:
      - ./data/data-mongo-cypress:/data/db
  
  director:
    image: agoldis/sorry-cypress-director:2.4.2
    environment:
      DASHBOARD_URL: http://localhost:8484
      EXECUTION_DRIVER: '../execution/mongo/driver'
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      SCREENSHOTS_DRIVER: '../screenshots/minio.driver'
      MINIO_ACCESS_KEY: '<change-me>'
      MINIO_SECRET_KEY: '<change-me>'
      MINIO_ENDPOINT: 'storage'
      MINIO_URL: 'https://jems.interact-eu.net/'
      MINIO_PORT: '9111'
      MINIO_USESSL: 'true'
      MINIO_BUCKET: sorry-cypress
    ports:
      - 1212:1234
    depends_on:
      - mongo

  api:
    image: agoldis/sorry-cypress-api:2.4.2
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      APOLLO_PLAYGROUND: 'false'
    ports:
      - 4040:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:2.4.2
    environment:
      GRAPHQL_SCHEMA_URL: http://jems.interact-eu.net:4040
      GRAPHQL_CLIENT_CREDENTIALS: ''
      PORT: 8080
      CI_URL: ''
    ports:
      - 8484:8080
    depends_on:
      - mongo
      - api

  storage:
    image: minio/minio
    hostname: 'storage'
    environment:
      MINIO_ROOT_USER: '<change-me>'
      MINIO_ROOT_PASSWORD: '<change-me>'
    volumes:
      - ./data/data-minio-cypress:/data
    command: server /data --address ":9111" --console-address ":9112"
    ports:
      - 9111:9111
      - 9112:9112

#  createbuckets:
#    image: minio/mc
#    depends_on:
#      - storage
#    entrypoint: >
#      /bin/sh -c "
#      sleep 10;
#      /usr/bin/mc config host add myminio http://storage:9111 <change-me> <change-me>;
#      /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress;
#      /usr/bin/mc mb myminio/sorry-cypress;
#      /usr/bin/mc policy set download myminio/sorry-cypress;
#      /usr/bin/mc policy set public myminio/sorry-cypress;
#      exit 0;
#      "