import './commands';
import './login.commands'
import './call.commands';
import './application.commands';
import './programme.commands';
import './system.commands';
import './partner-report.commands';
import './partner-report-control.commands';
import './controller.commands';
import './contracting.commands';
import './payments.commands';
