package io.cloudflight.jems.api.programme.dto.stateaid

enum class ProgrammeStateAidMeasure(val key: String) {
    GENERAL_DE_MINIMIS("General de minimis"),
    ROAD_FREIGHT_DE_MINIMIS("Road freight de minimis"),
    AGRICULTURAL_DE_MINIMIS("Agricultural de minimis"),
    FISHER_AND_AQUACULTURE_SECTOR_DE_MINIMIS("Fishery and aquaculture sector de minimis"),
    SGEI_DE_MINIMIS("SGEI de minimis"),
    GBER_ARTICLE_14("GBER Article 14"),
    GBER_ARTICLE_15("GBER Article 15"),
    GBER_ARTICLE_16("GBER Article 16"),
    GBER_ARTICLE_17("GBER Article 17"),
    GBER_ARTICLE_18("GBER Article 18"),
    GBER_ARTICLE_19("GBER Article 19"),
    GBER_ARTICLE_19A("GBER Article 19a"),
    GBER_ARTICLE_19B("GBER Article 19b"),
    GBER_ARTICLE_20("GBER Article 20"),
    GBER_ARTICLE_20A("GBER Article 20a"),
    GBER_ARTICLE_21("GBER Article 21"),
    GBER_ARTICLE_22("GBER Article 22"),
    GBER_ARTICLE_23("GBER Article 23"),
    GBER_ARTICLE_24("GBER Article 24"),
    GBER_ARTICLE_25_PAR_A("GBER Article 25 par. (a)"),
    GBER_ARTICLE_25_PAR_B("GBER Article 25 par. (b)"),
    GBER_ARTICLE_25_PAR_C("GBER Article 25 par. (c)"),
    GBER_ARTICLE_25_PAR_D("GBER Article 25 par. (d)"),
    GBER_ARTICLE_25A("GBER Article 25a"),
    GBER_ARTICLE_25B("GBER Article 25b"),
    GBER_ARTICLE_25C("GBER Article 25c"),
    GBER_ARTICLE_25D("GBER Article 25d"),
    GBER_ARTICLE_26("GBER Article 26"),
    GBER_ARTICLE_27("GBER Article 27"),
    GBER_ARTICLE_28("GBER Article 28"),
    GBER_ARTICLE_29("GBER Article 29"),
    GBER_ARTICLE_30("GBER Article 30"),
    GBER_ARTICLE_31("GBER Article 31"),
    GBER_ARTICLE_32("GBER Article 32"),
    GBER_ARTICLE_33("GBER Article 33"),
    GBER_ARTICLE_34("GBER Article 34"),
    GBER_ARTICLE_35("GBER Article 35"),
    GBER_ARTICLE_36("GBER Article 36"),
    GBER_ARTICLE_36A("GBER Article 36a"),
    GBER_ARTICLE_37("GBER Article 37"),
    GBER_ARTICLE_38("GBER Article 38"),
    GBER_ARTICLE_39("GBER Article 39"),
    GBER_ARTICLE_40("GBER Article 40"),
    GBER_ARTICLE_41("GBER Article 41"),
    GBER_ARTICLE_42("GBER Article 42"),
    GBER_ARTICLE_43("GBER Article 43"),
    GBER_ARTICLE_44("GBER Article 44"),
    GBER_ARTICLE_45("GBER Article 45"),
    GBER_ARTICLE_46("GBER Article 46"),
    GBER_ARTICLE_47("GBER Article 47"),
    GBER_ARTICLE_48("GBER Article 48"),
    GBER_ARTICLE_49("GBER Article 49"),
    GBER_ARTICLE_50("GBER Article 50"),
    GBER_ARTICLE_51("GBER Article 51"),
    GBER_ARTICLE_52("GBER Article 52"),
    GBER_ARTICLE_52A("GBER Article 52a"),
    GBER_ARTICLE_52B("GBER Article 52b"),
    GBER_ARTICLE_52C("GBER Article 52c"),
    GBER_ARTICLE_53("GBER Article 53"),
    GBER_ARTICLE_54("GBER Article 54"),
    GBER_ARTICLE_55("GBER Article 55"),
    GBER_ARTICLE_56("GBER Article 56"),
    GBER_ARTICLE_56A("GBER Article 56a"),
    GBER_ARTICLE_56B("GBER Article 56b"),
    GBER_ARTICLE_56C("GBER Article 56c"),
    GBER_ARTICLE_56E("GBER Article 56e"),
    GBER_ARTICLE_56F("GBER Article 56f"),
    INDIRECT_AID("Indirect aid"),
    RDI_FRAMEWORK("RDI Framework"),
    SGEI_FRAMEWORK("SGEI Framework"),
    OTHER_1("Other 1"),
    OTHER_2("Other 2"),
    OTHER_3("Other 3"),
}
