export class ProgrammeOutputIndicatorConstants {
  static indicatorCodes = ['RCO01', 'RCO02', 'RCO03', 'RCO04', 'RCO05', 'RCO06', 'RCO08', 'RCO10', 'RCO96', 'RCO12',
                           'RCO13', 'RCO14', 'RCO15', 'RCO16', 'RCO17', 'RCO101', 'RCO102', 'RCO18', 'RCO19', 'RCO20',
                           'RCO22', 'RCO97', 'RCO23', 'RCO98', 'RCO24', 'RCO25', 'RCO26', 'RCO27', 'RCO28', 'RCO30',
                           'RCO31', 'RCO32', 'RCO34', 'RCO36', 'RCO37', 'RCO99', 'RCO38', 'RCO39', 'RCO41', 'RCO42',
                           'RCO43', 'RCO44', 'RCO45', 'RCO46', 'RCO47', 'RCO48', 'RCO49', 'RCO50', 'RCO51', 'RCO52',
                           'RCO53', 'RCO54', 'RCO100', 'RCO55', 'RCO56', 'RCO57', 'RCO58', 'RCO59', 'RCO60', 'RCO61',
                           'RCO63', 'RCO64', 'RCO65', 'RCO66', 'RCO67', 'RCO69', 'RCO70', 'RCO74', 'RCO75', 'RCO76',
                           'RCO77', 'RCO80', 'RCO95', 'RCO81', 'RCO82', 'RCO83', 'RCO84', 'RCO85', 'RCO96', 'RCO86',
                           'RCO87', 'RCO88', 'RCO89', 'RCO90'
  ];

  static indicatorNames = [
    'Enterprises supported (of which: micro, small, medium, large)',
    'Enterprises supported by grants',
    'Enterprises supported by financial instruments',
    'Enterprises with non-financial support',
    'Start-ups supported',
    'Researchers working in supported research facilities Research institutions participating in joint research projects ',
    'Nominal value of research and innovation equipment',
    'Enterprises cooperating with research institutions',
    'Interregional investments in EU projects',
    'Enterprises supported to digitise their products and services',
    'Digital services and products developed for enterprises',
    'Public institutions supported to develop digital services and applications',
    'Capacity of incubation created',
    'Stakeholders participating in entrepreneurial discovery process',
    'Investments in regional/ local ecosystems for skills development',
    'SMEs investing in skills development',
    'SMEs investing in training management systems',
    'Households supported to improve energy performance of their dwelling',
    'Public buildings supported to improve energy performance',
    'District heating network lines newly constructed or improved',
    'Additional production capacity for renewable energy  (of which: electricity, thermal) ',
    'Number of energy communities and renewable energy communities supported',
    'Digital management systems for smart grids',
    'Households supported to use smart energy grids',
    'New or upgraded disaster monitoring, preparedness, warning and response systems',
    'Coastal strip, river banks and lakeshores, and landslide protection newly built or consolidated to protect people, assets and the natural environment',
    'Green infrastructure built for adaptation to climate change',
    'National/ regional/ local strategies addressing climate change adaptation',
    'Areas covered by protection measures against forest fires',
    'Length of new or consolidated pipes for  household water connections',
    'Length of sewage collection networks newly constructed or consolidated',
    'New or upgraded capacity for waste water treatment',
    'Additional capacity for waste recycling',
    'Surface area of green infrastructure supported in urban areas',
    'Surface of Natura sites covered by protection and restoration measures in accordance with the prioritised action framework',
    'Surface area outside Natura sites covered by protection and restoration measures',
    'Surface area of rehabilitated land supported',
    'Systems for monitoring air pollution installed',
    'Additional households with broadband access of very high capacity',
    'Additional enterprises with broadband access of very high capacity',
    'Capacity of cultural and tourism infrastructure supported',
    'Length of new roads supported - other',
    'Length of roads reconstructed or upgraded - TEN-T',
    'Length of roads reconstructed or upgraded - other',
    'Length of new rail supported - TEN-T',
    'Length of new rail supported - other',
    'Length of rail reconstructed or upgraded - TEN-T',
    'Length of rail reconstructed or upgraded - other',
    'Length of new or upgraded inland waterways - TEN-T',
    'Length of new or upgraded inland waterways - other',
    'Railways stations and facilities new or upgraded',
    'Intermodal connections new or upgraded',
    'Number of ports supported',
    'Length of tram and metro lines - new',
    'Length of tram and metro lines - reconstructed/ upgraded',
    'Environmentally friendly rolling stock for public transport',
    'Dedicated cycling infrastructure supported',
    'Alternative fuels infrastructure (refuelling/ recharging points) supported',
    'Cities and towns with new or upgraded digitised urban transport systems',
    'Annual unemployed persons served by enhanced facilities for employment services (capacity)',
    'Capacity of temporary reception infrastructure created',
    'Capacity of rehabilitated housing – migrants, refugees and persons under or applying for international protection',
    'Capacity of rehabilitated housing - other',
    'Classroom capacity of supported childcare infrastructure (new or upgraded)_x000D_ _x000D_',
    'Classroom capacity of supported education infrastructure (new or upgraded)',
    'Capacity of supported health care infrastructure',
    'Capacity of supported social infrastructure (other than housing)',
    'Population covered by strategies for integrated urban development',
    'Integrated strategies for urban development',
    'Collaborative projects',
    'Capacity of cultural and tourism infrastructure supported',
    'Community-led local development strategies for local development',
    'Staff financed by ERDF and Cohesion Fund',
    'Participants in cross-border mobility initiatives',
    'Participants in joint actions promoting gender equality, equal opportunities and social inclusion',
    'Joint strategies/ action plans developed or implemented',
    'Joint pilot activities implemented in projects',
    'Participants in joint training schemes',
    'Legal or administrative obstacles identified',
    'Joint administrative or legal agreements signed',
    'Organisations cooperating across borders',
    'Projects across national borders for peer-learning to enhance cooperation activities',
    'Projects across borders to improve multilevel governance',
    'Projects across national borders leading to networks/clusters',
  ];

  static measurementUnits = [
    'annual FTEs',
    'cities and towns',
    'co-generation units',
    'cultural and tourism sites',
    'dwellings',
    'enterprises',
    'euro',
    'events',
    'hectares',
    'intermodal connections',
    'km',
    'Legal or administrative agreement',
    'MW',
    'MWh',
    'organisations',
    'participation',
    'participations of institutional stakeholders',
    'passengers',
    'persons',
    'persons/year',
    'pilot actions',
    'population equivalent',
    'projects',
    'public institutions',
    'refuelling/recharging points',
    'renewable energy communities',
    'research institutions',
    'solution identified for obstacles',
    'solutions developed',
    'square metres',
    'stations and stops',
    'strategies',
    'strategy/action plan',
    'systems',
    'tonnes/year',
  ];
}
