api:
  base-path: /api

spring:
  flyway:
    out-of-order: true
  messages:
    basename: classpath:/messages
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/jemsdb}"
    username: root
    password: "${SPRING_DATASOURCE_PASSWORD:Mariadb@2020}"
    driver-class-name: org.mariadb.jdbc.Driver
    jpa:
      database: mariadb
      open-in-view: false
      hibernate:
        ddl-auto: update
      show-sql: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

audit-service:
  enabled: "${AUDIT_ENABLED:false}"
  url-and-port: "${AUDIT_ELASTICSEARCH_URL_AND_PORT:localhost:9200}"

minio-storage:
  endpoint: "${MINIO_URL_AND_PORT:http://localhost:9000}"
  accessKey: "${MINIO_ACCESS_KEY:jemsminio}"
  secretKey: "${MINIO_SECRET_KEY:Minio@2020}"
server:
  servlet:
    session:
      timeout: 60m

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  health:
    elasticsearch:
      enabled: "${AUDIT_ENABLED:false}"
info:
  helpdesk-url: "https://helpdesk.interact-eu.net"
