package io.cloudflight.jems.api.plugin.dto

enum class PluginTypeDTO {
    ALL,
    PROGRAMME_DATA_EXPORT,
    PRE_SUBMISSION_CHECK,
    APPLICATION_FORM_EXPORT,
    BUDGET_EXPORT,
    REPORT_PARTNER_CHECK,
    PARTNER_REPORT_EXPORT,
    PARTNER_CONTROL_REPORT_CERTIFICATE,
    PARTNER_CONTROL_REPORT_EXPORT,
    PARTNER_CONTROL_REPORT_CHECK,
    PARTNER_CONTROL_RISK_BASED_SAMPLING,
    REPORT_PROJECT_CHECK,
    REPORT_PROJECT_EXPORT,
    CHECKLIST_EXPORT,
}
