package io.cloudflight.jems.api.plugin.dto

enum class PluginTypeDTO {
    ALL,
    PROGRAMME_DATA_EXPORT,
    PRE_SUBMISSION_CHECK,
    APPLICATION_FORM_EXPORT,
    BUDGET_EXPORT,
    REPORT_PARTNER_CHECK,
    PARTNER_REPORT_EXPORT,
    PARTNER_CONTROL_CERTIFICATE_EXPORT
}
