api:
  base-path: /api

spring:
  flyway:
    out-of-order: true
  messages:
    basename: classpath:/messages
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/ems}"
    username: root
    password: "${SPRING_DATASOURCE_PASSWORD:emspass}"
    driver-class-name: org.mariadb.jdbc.Driver
    jpa:
      database: mariadb
      open-in-view: false
      hibernate:
        ddl-auto: update
      show-sql: false
