package io.cloudflight.jems.server.project.service.partner.budget.get_budget_general_costs.get_budget_infrastructure_and_works_costs

import io.cloudflight.jems.server.project.service.partner.budget.get_budget_general_costs.GetBudgetGeneralCostsInteractor

interface GetBudgetInfrastructureAndWorksCostsInteractor : GetBudgetGeneralCostsInteractor
