export enum ReportFileCategoryTypeEnum {
  REPORT = 'REPORT',
  WORKPLAN = 'WORKPLAN',
  EXPENDITURE = 'EXPENDITURE',
  PROCUREMENT = 'PROCUREMENT',
  CONTRIBUTION = 'CONTRIBUTION',
  ALL = 'ALL',
  OUTPUT = 'OUTPUT',
  ACTIVITY = 'ACTIVITY',
  DELIVERABLE= 'DELIVERABLE'
}
