package io.cloudflight.jems.server.project.service.partner.budget.get_budget_general_costs.get_budget_external_expertise_and_services

import io.cloudflight.jems.server.project.service.partner.budget.get_budget_general_costs.GetBudgetGeneralCostsInteractor

interface GetBudgetExternalExpertiseAndServicesCostsInteractor : GetBudgetGeneralCostsInteractor


