package io.cloudflight.jems.api.audit.dto

enum class AuditAction {
    // package CALL
    CALL_ADDED,
    CALL_CONFIGURATION_CHANGED,
    CALL_PUBLISHED,

    // package CURRENCY
    CURRENCY_IMPORT,

    // package NUTS
    NUTS_DATASET_DOWNLOAD,

    // package PROGRAMME
    PROGRAMME_PRIORITY_ADDED,
    PROGRAMME_PRIORITY_UPDATED,
    PROGRAMME_BASIC_DATA_EDITED,
    PROGRAMME_NUTS_AREA_CHANGED,
    PROGRAMME_FUNDS_CHANGED,
    PROGRAMME_UI_LANGUAGES_CHANGED,
    PROGRAMME_INPUT_LANGUAGES_CHANGED,
    PROGRAMME_STRATEGIES_CHANGED,
    PROGRAMME_TRANSLATION_FILE_UPLOADED,
    PROGRAMME_STATE_AID_CHANGED,

    // PROGRAMME - Indicators
    PROGRAMME_INDICATOR_ADDED,
    PROGRAMME_INDICATOR_EDITED,

    // PROGRAMME - Cost Options:
    PROGRAMME_LUMP_SUM_ADDED,
    PROGRAMME_LUMP_SUM_CHANGED,
    PROGRAMME_UNIT_COST_ADDED,
    PROGRAMME_UNIT_COST_CHANGED,

    // package PROJECT
    APPLICATION_STATUS_CHANGED,
    APPLICATION_VERSION_SNAPSHOT_CREATED,
    APPLICATION_VERSION_RECORDED,
    CALL_ALREADY_ENDED,
    QUALITY_ASSESSMENT_CONCLUDED,
    ELIGIBILITY_ASSESSMENT_CONCLUDED,
    APPLICATION_SUBMISSION_UNSUCCESSFUL,
    PROJECT_USER_ASSIGNMENT_PROGRAMME,
    PROJECT_USER_ASSIGNMENT_APPLICANTS,
    PROJECT_CONTRACT_MONITORING_CHANGED,

    // messages related to FILEs
    PROJECT_FILE_DELETED,
    PROJECT_FILE_DOWNLOADED_SUCCESSFULLY,
    PROJECT_FILE_DOWNLOADED_FAILED,
    PROJECT_FILE_UPLOADED_SUCCESSFULLY,
    PROJECT_FILE_UPLOAD_FAILED,
    PROJECT_FILE_DESCRIPTION_CHANGED,

    // package SECURITY
    USER_LOGGED_IN,
    USER_LOGGED_OUT,
    USER_SESSION_EXPIRED,

    // package USER
    USER_ADDED,
    USER_REGISTERED,
    USER_DATA_CHANGED,
    PASSWORD_CHANGED,
    ROLE_PRIVILEGES_CREATED,
    ROLE_PRIVILEGES_CHANGED,

    //package LEGAL STATUS
    LEGAL_STATUS_EDITED,

    //plugin
    PLUGIN_CALLED,
    PLUGIN_EXECUTED,

    //email
    MAIL_SENT,
    MAIL_NOT_SENT,

    // report
    PARTNER_REPORT_ADDED,
    PARTNER_REPORT_SUBMITTED,
    CONTROL_ONGOING,

    // Checklist
    ASSESSMENT_CHECKLIST_STATUS_CHANGE,
    ASSESSMENT_CHECKLIST_DELETED,
    ASSESSMENT_CHECKLIST_CONSOLIDATION_CHANGE,
    ASSESSMENT_CHECKLIST_VISIBILITY_CHANGE,
    CHECKLIST_IS_CREATED,
    CHECKLIST_IS_DELETED,

    // Controllers
    CONTROLLER_INSTITUTION_CHANGED,
    INSTITUTION_PARTNER_ASSIGNMENT_CHANGED,
    INSTITUTION_PARTNER_ASSIGNMENT_DROPPED
}
