package io.cloudflight.ems.entity

enum class AuditAction {
    APPLICATION_STATUS_CHANGED,
    PROJECT_FILE_DELETE,
    USER_LOGGED_IN,
    USER_LOGGED_OUT,
    USER_SESSION_EXPIRED,
    USER_CREATED,
    USER_REGISTERED,
    USER_ROLE_CHANGED,
    PASSWORD_CHANGED,
    USER_DATA_CHANGED,
}
